POST  https://crud-node-postgre.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 0110",
    "description": "Esse é o primeiro video",
    "duration": 180
}

### 

GET  https://crud-node-postgre.onrender.com/videos

###

PUT  https://crud-node-postgre.onrender.com/videos/f0c10d23-c41c-4a09-8a31-fc115654ce98
Content-Type: application/json

{
    "title": "Teste Dep",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://crud-node-postgre.onrender.com/videos/f0c10d23-c41c-4a09-8a31-fc115654ce98